
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table1;
	private global::Gtk.Button button1;
	private global::Gtk.Entry E1;
	private global::Gtk.Label label1;
	private global::Gtk.Table table2;
	private global::Gtk.Button button2;
	private global::Gtk.ComboBox CB1;
	private global::Gtk.Entry E2;
	private global::Gtk.Entry E3;
	private global::Gtk.Entry E4;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView TrV;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(10));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w2 = new global::Gtk.HBox ();
		w2.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w3 = new global::Gtk.Image ();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
		w2.Add (w3);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.LabelProp = global::Mono.Unix.Catalog.GetString ("Seleccionar");
		w5.UseUnderline = true;
		w2.Add (w5);
		w1.Add (w2);
		this.button1.Add (w1);
		this.table1.Add (this.button1);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.button1]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E1 = new global::Gtk.Entry ();
		this.E1.CanFocus = true;
		this.E1.Name = "E1";
		this.E1.IsEditable = true;
		this.E1.InvisibleChar = '•';
		this.table1.Add (this.E1);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.E1]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Directorio");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(5));
		// Container child table2.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		// Container child button2.Gtk.Container+ContainerChild
		global::Gtk.Alignment w13 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w14 = new global::Gtk.HBox ();
		w14.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w15 = new global::Gtk.Image ();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
		w14.Add (w15);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w17 = new global::Gtk.Label ();
		w17.LabelProp = global::Mono.Unix.Catalog.GetString ("Buscar");
		w17.UseUnderline = true;
		w14.Add (w17);
		w13.Add (w14);
		this.button2.Add (w13);
		this.table2.Add (this.button2);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.button2]));
		w21.TopAttach = ((uint)(2));
		w21.BottomAttach = ((uint)(3));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.CB1 = global::Gtk.ComboBox.NewText ();
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Ninguno"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Tamaño"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Fecha"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Extencion"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Tamaño y Fecha"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Tamaño y Extension"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Fecha y Extencion"));
		this.CB1.AppendText (global::Mono.Unix.Catalog.GetString ("Tamaño, Fecha y Extencion"));
		this.CB1.Name = "CB1";
		this.CB1.Active = 0;
		this.table2.Add (this.CB1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.CB1]));
		w22.TopAttach = ((uint)(2));
		w22.BottomAttach = ((uint)(3));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.E2 = new global::Gtk.Entry ();
		this.E2.CanFocus = true;
		this.E2.Name = "E2";
		this.E2.IsEditable = true;
		this.E2.InvisibleChar = '•';
		this.table2.Add (this.E2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.E2]));
		w23.TopAttach = ((uint)(1));
		w23.BottomAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.E3 = new global::Gtk.Entry ();
		this.E3.CanFocus = true;
		this.E3.Name = "E3";
		this.E3.IsEditable = true;
		this.E3.InvisibleChar = '•';
		this.table2.Add (this.E3);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.E3]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.E4 = new global::Gtk.Entry ();
		this.E4.CanFocus = true;
		this.E4.Name = "E4";
		this.E4.IsEditable = true;
		this.E4.InvisibleChar = '•';
		this.table2.Add (this.E4);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.E4]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tamaño");
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Fecha");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w27.LeftAttach = ((uint)(1));
		w27.RightAttach = ((uint)(2));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Extencion");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w28.LeftAttach = ((uint)(2));
		w28.RightAttach = ((uint)(3));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Filtrar por:");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w29.TopAttach = ((uint)(2));
		w29.BottomAttach = ((uint)(3));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TrV = new global::Gtk.TreeView ();
		this.TrV.CanFocus = true;
		this.TrV.Name = "TrV";
		this.GtkScrolledWindow.Add (this.TrV);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w32.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 561;
		this.DefaultHeight = 425;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
