
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table1;
	private global::Gtk.Entry E1;
	private global::Gtk.Entry E2;
	private global::Gtk.Entry E3;
	private global::Gtk.Entry E4;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.Label label7;
	private global::Gtk.Table table2;
	private global::Gtk.Button Aceptar;
	private global::Gtk.Button Agregar1;
	private global::Gtk.ComboBox Cb1;
	private global::Gtk.Button Eliminar;
	private global::Gtk.Entry Er;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Button Limpiar1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView Tw;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.E1 = new global::Gtk.Entry ();
		this.E1.CanFocus = true;
		this.E1.Name = "E1";
		this.E1.IsEditable = true;
		this.E1.InvisibleChar = '•';
		this.table1.Add (this.E1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.E1]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E2 = new global::Gtk.Entry ();
		this.E2.CanFocus = true;
		this.E2.Name = "E2";
		this.E2.IsEditable = true;
		this.E2.InvisibleChar = '•';
		this.table1.Add (this.E2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.E2]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E3 = new global::Gtk.Entry ();
		this.E3.CanFocus = true;
		this.E3.Name = "E3";
		this.E3.IsEditable = true;
		this.E3.InvisibleChar = '•';
		this.table1.Add (this.E3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.E3]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E4 = new global::Gtk.Entry ();
		this.E4.CanFocus = true;
		this.E4.Name = "E4";
		this.E4.IsEditable = true;
		this.E4.InvisibleChar = '•';
		this.table1.Add (this.E4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.E4]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Asignatura");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Nota 1");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Nota 2");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Nota 3");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w8.LeftAttach = ((uint)(3));
		w8.RightAttach = ((uint)(4));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(90));
		// Container child table2.Gtk.Table+TableChild
		this.Aceptar = new global::Gtk.Button ();
		this.Aceptar.CanFocus = true;
		this.Aceptar.Name = "Aceptar";
		this.Aceptar.UseUnderline = true;
		this.Aceptar.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.table2.Add (this.Aceptar);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.Aceptar]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.Agregar1 = new global::Gtk.Button ();
		this.Agregar1.CanFocus = true;
		this.Agregar1.Name = "Agregar1";
		this.Agregar1.UseUnderline = true;
		this.Agregar1.Label = global::Mono.Unix.Catalog.GetString ("Agregar");
		this.table2.Add (this.Agregar1);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.Agregar1]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.Cb1 = global::Gtk.ComboBox.NewText ();
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("Ordenar"));
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("Promedio"));
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("Aprobadas"));
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("Reprobadas"));
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("% Aprobadas"));
		this.Cb1.AppendText (global::Mono.Unix.Catalog.GetString ("% Reprobadas"));
		this.Cb1.Name = "Cb1";
		this.Cb1.Active = 0;
		this.table2.Add (this.Cb1);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.Cb1]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.Eliminar = new global::Gtk.Button ();
		this.Eliminar.CanFocus = true;
		this.Eliminar.Name = "Eliminar";
		this.Eliminar.UseUnderline = true;
		this.Eliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
		this.table2.Add (this.Eliminar);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.Eliminar]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.Er = new global::Gtk.Entry ();
		this.Er.CanFocus = true;
		this.Er.Name = "Er";
		this.Er.IsEditable = false;
		this.Er.InvisibleChar = '•';
		this.table2.Add (this.Er);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.Er]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(2));
		w14.RightAttach = ((uint)(3));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.table2.Add (this.label8);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Operacion");
		this.table2.Add (this.label9);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.Limpiar1 = new global::Gtk.Button ();
		this.Limpiar1.CanFocus = true;
		this.Limpiar1.Name = "Limpiar1";
		this.Limpiar1.UseUnderline = true;
		this.Limpiar1.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.table2.Add (this.Limpiar1);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.Limpiar1]));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Tw = new global::Gtk.TreeView ();
		this.Tw.CanFocus = true;
		this.Tw.Name = "Tw";
		this.GtkScrolledWindow.Add (this.Tw);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w20.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 688;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Limpiar1.Clicked += new global::System.EventHandler (this.OnLimpiar1Clicked);
		this.Eliminar.Clicked += new global::System.EventHandler (this.OnEliminarClicked);
		this.Agregar1.Clicked += new global::System.EventHandler (this.OnAgregar1Clicked);
		this.Aceptar.Clicked += new global::System.EventHandler (this.OnAceptarClicked);
	}
}
