
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Label apellidos;
	
	private global::Gtk.Label Cedula;
	
	private global::Gtk.Entry E1;
	
	private global::Gtk.Entry E2;
	
	private global::Gtk.Entry E3;
	
	private global::Gtk.Entry E4;
	
	private global::Gtk.Entry E5;
	
	private global::Gtk.Entry E6;
	
	private global::Gtk.Label nombre;
	
	private global::Gtk.Label programa;
	
	private global::Gtk.Label promedio;
	
	private global::Gtk.Label semestre;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button agregar;
	
	private global::Gtk.Button cargar;
	
	private global::Gtk.Button eliminar;
	
	private global::Gtk.Button guardar;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView Trv;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.apellidos = new global::Gtk.Label ();
		this.apellidos.Name = "apellidos";
		this.apellidos.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellidos");
		this.table1.Add (this.apellidos);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.apellidos]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Cedula = new global::Gtk.Label ();
		this.Cedula.Name = "Cedula";
		this.Cedula.LabelProp = global::Mono.Unix.Catalog.GetString ("Cedula");
		this.table1.Add (this.Cedula);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.Cedula]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E1 = new global::Gtk.Entry ();
		this.E1.CanFocus = true;
		this.E1.Name = "E1";
		this.E1.IsEditable = true;
		this.E1.InvisibleChar = '●';
		this.table1.Add (this.E1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.E1]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E2 = new global::Gtk.Entry ();
		this.E2.CanFocus = true;
		this.E2.Name = "E2";
		this.E2.IsEditable = true;
		this.E2.InvisibleChar = '●';
		this.table1.Add (this.E2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.E2]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E3 = new global::Gtk.Entry ();
		this.E3.CanFocus = true;
		this.E3.Name = "E3";
		this.E3.IsEditable = true;
		this.E3.InvisibleChar = '●';
		this.table1.Add (this.E3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.E3]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E4 = new global::Gtk.Entry ();
		this.E4.CanFocus = true;
		this.E4.Name = "E4";
		this.E4.IsEditable = true;
		this.E4.InvisibleChar = '●';
		this.table1.Add (this.E4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.E4]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E5 = new global::Gtk.Entry ();
		this.E5.CanFocus = true;
		this.E5.Name = "E5";
		this.E5.IsEditable = true;
		this.E5.InvisibleChar = '●';
		this.table1.Add (this.E5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.E5]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.E6 = new global::Gtk.Entry ();
		this.E6.CanFocus = true;
		this.E6.Name = "E6";
		this.E6.IsEditable = true;
		this.E6.InvisibleChar = '●';
		this.table1.Add (this.E6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.E6]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.nombre = new global::Gtk.Label ();
		this.nombre.Name = "nombre";
		this.nombre.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombres");
		this.table1.Add (this.nombre);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.nombre]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.programa = new global::Gtk.Label ();
		this.programa.Name = "programa";
		this.programa.LabelProp = global::Mono.Unix.Catalog.GetString ("Programa");
		this.table1.Add (this.programa);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.programa]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.promedio = new global::Gtk.Label ();
		this.promedio.Name = "promedio";
		this.promedio.LabelProp = global::Mono.Unix.Catalog.GetString ("Promedio");
		this.table1.Add (this.promedio);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.promedio]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.semestre = new global::Gtk.Label ();
		this.semestre.Name = "semestre";
		this.semestre.LabelProp = global::Mono.Unix.Catalog.GetString ("Semestre");
		this.table1.Add (this.semestre);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.semestre]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(1)), ((uint)(5)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.agregar = new global::Gtk.Button ();
		this.agregar.CanFocus = true;
		this.agregar.Name = "agregar";
		this.agregar.UseUnderline = true;
		this.agregar.Label = global::Mono.Unix.Catalog.GetString ("Agregar");
		this.table2.Add (this.agregar);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.agregar]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.cargar = new global::Gtk.Button ();
		this.cargar.CanFocus = true;
		this.cargar.Name = "cargar";
		this.cargar.UseUnderline = true;
		this.cargar.Label = global::Mono.Unix.Catalog.GetString ("Cargar");
		this.table2.Add (this.cargar);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.cargar]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.eliminar = new global::Gtk.Button ();
		this.eliminar.CanFocus = true;
		this.eliminar.Name = "eliminar";
		this.eliminar.UseUnderline = true;
		this.eliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
		this.table2.Add (this.eliminar);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.eliminar]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.guardar = new global::Gtk.Button ();
		this.guardar.CanFocus = true;
		this.guardar.Name = "guardar";
		this.guardar.UseUnderline = true;
		this.guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
		this.table2.Add (this.guardar);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.guardar]));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Trv = new global::Gtk.TreeView ();
		this.Trv.CanFocus = true;
		this.Trv.Name = "Trv";
		this.GtkScrolledWindow.Add (this.Trv);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w20.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 595;
		this.DefaultHeight = 441;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.guardar.Clicked += new global::System.EventHandler (this.OnGuardarClicked);
		this.eliminar.Clicked += new global::System.EventHandler (this.OnEliminarClicked);
		this.cargar.Clicked += new global::System.EventHandler (this.OnCargarClicked);
		this.agregar.Clicked += new global::System.EventHandler (this.OnAgregarClicked);
	}
}
